sonar.projectName=iojournal
sonar.projectDescription=Bounded logging library for C23
sonar.sourceEncoding=UTF-8
sonar.sources=include,src,examples
sonar.tests=tests
sonar.exclusions=tests/third_party/**,build/**,docs/**,deploy/**,tests/artifacts/**
sonar.c.file.suffixes=.c,.h
